import { chromium } from '@playwright/test';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, reducedMotion: 'no-preference' });
const errors=[];
page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.message)});
page.on('console',m=>{if(m.type()==='error') console.log('CONSOLE ERROR',m.text())});
await page.goto('http://127.0.0.1:3003');
await page.locator('.core-ready').waitFor({timeout:20000}).catch(async e=>{await page.screenshot({path:'docs/review/hero-failure.png'});throw e});
await page.waitForTimeout(1200);
await page.screenshot({path:'docs/review/hero-desktop.png'});
await page.getByRole('button',{name:'02 Unfold',exact:true}).click();
await page.waitForTimeout(1800);
await page.screenshot({path:'docs/review/hero-unfold.png'});
await page.getByRole('button',{name:'03 Enter world',exact:true}).click();
await page.waitForTimeout(1800);
await page.screenshot({path:'docs/review/hero-world.png'});
await page.setViewportSize({width:390,height:844});
await page.goto('http://127.0.0.1:3003');
await page.locator('.core-ready').waitFor();
await page.waitForTimeout(1000);
await page.screenshot({path:'docs/review/hero-mobile.png'});
await page.getByRole('button',{name:'02 Unfold',exact:true}).click();
await page.waitForTimeout(1800);
await page.screenshot({path:'docs/review/hero-mobile-unfold.png'});
for (const [width,height] of [[320,740],[768,1024],[720,450]]) {
  await page.setViewportSize({width,height});
  await page.goto('http://127.0.0.1:3003');
  await page.locator(height > 600 ? '.core-ready' : '.core-still').waitFor({timeout:20000});
  await page.waitForTimeout(800);
  await page.screenshot({path:`docs/review/hero-${width}.png`});
}
console.log({errors});
await browser.close();
