import sharp from 'sharp';import fs from 'node:fs';
fs.mkdirSync('docs/review',{recursive:true});fs.mkdirSync('public/media',{recursive:true});
let list=JSON.parse(fs.readFileSync('assets/manifest.json'));let seen=new Set();let unique=list.filter(a=>a.recovered&&!seen.has(a.local)&&seen.add(a.local));
for(let a of unique){try{let m=await sharp(a.local).metadata();a.width=m.width;a.height=m.height;a.quality=m.width>=1200?'High resolution':m.width>=600?'Usable, limited crop':'Small; logo or reference only';a.usability=a.type==='svg'?'Brand source':'Review for correct placement';a.purpose=a.local.split('/')[2];}catch{a.usability='Video, inspect before use'};a.bytes=fs.statSync(a.local).size;}
fs.writeFileSync('assets/manifest.json',JSON.stringify(unique,null,2));
let selection=unique.filter(a=>/single|vertical-cabinet|home-newly.*Dragon|Thumbnails_Raise|Home-about-big|1_sunscape|cabinet.*banner|pinnacle|ALTITUDE/.test(a.id)).slice(0,18);
let tiles=[];for(let i=0;i<selection.length;i++){let a=selection[i];let img=await sharp(a.local).resize(260,230,{fit:'contain',background:'#252525'}).png().toBuffer();tiles.push({input:img,left:(i%4)*280,top:Math.floor(i/4)*270});let label=Buffer.from(`<svg width="280" height="35"><text x="5" y="16" fill="white" font-size="10">${a.id.slice(0,42)}</text></svg>`);tiles.push({input:label,left:(i%4)*280,top:Math.floor(i/4)*270+232});}
await sharp({create:{width:1120,height:Math.ceil(selection.length/4)*270,channels:3,background:'#181818'}}).composite(tiles).png().toFile('docs/review/recovered-contact-sheet.png');
fs.appendFileSync('docs/MEDIA-RECOVERY.md','\n## Recovered inventory\n'+unique.length+' unique local originals (HTTP/HTTPS duplicate discoveries consolidated).\n\n|Asset|Original URL|Page/source|Type|Dimensions|Bytes|Quality / usability|Replacement|\n|---|---|---|---|---|---|---|---|\n'+unique.map(a=>`|${a.id}|${a.original}|${a.source.join(', ')}|${a.type}|${a.width??'—'} × ${a.height??'—'}|${a.bytes}|${a.quality??'Video'}; ${a.usability}|${a.replacementRequired}|`).join('\n'));
console.log(unique.length,'unique assets; contact sheet ready');
