from pathlib import Path
def w(p,s):Path(p).parent.mkdir(parents=True,exist_ok=True);Path(p).write_text(s.strip()+'\n')
items=[
('TP-001','Blender / product model','Home prototype; /cabinets/','Altitude hero/focus/screen entry','Recognizable real Altitude with independent display and glass','/cabinets/; vertical-cabinet-with-tierplay-logo.webp','Measured real-world cabinet dimensions; meters; dimensions not supplied','Front 3/4, target lens50mm equivalent, camera1.35m subject to approved product dimensions','Large soft key left; controlled rim right; subtle overhead strip','Reference-verified shell, trim, glass, controls; do not assume brushed aluminum if reference does not establish it','None; screen media separate','No','GLB + editable .blend + texture sources','Provisional LOD0≤120k triangles, LOD1≤60k, LOD2≤20k; ≤6MB compressed with textures; measure silhouette loss','Yes: LOD2, 1K textures and approved portrait still','BLOCKED BY ASSET: TP-001. BLENDER ASSET REQUIRED. Exact orthographic front/side/rear/top, dimensions, screen curvature/normal and component photos needed. No stacked-box substitute.'),
('TP-002','Blender / product model','/cabinets/; later home showcase','Pinnacle presentation','Preserve curved cabinet identity and separate screen geometry','/cabinets/; Curved-single-side-with-tierplay-logo.webp','Real meters and verified curved-display radius; not supplied','Authored shallow arc around real product bounds','Soft controlled material sweep, neutral environment','As per approved physical sample/photos','None','No','GLB + .blend + PBR texture sources','Same initial LOD/bundle targets as TP-001; load only when requested','Yes','BLENDER ASSET REQUIRED. Do not infer geometry or count of screens from generated images.'),
('TP-003','Blender / internal assembly','Technology / Cabinets','Exploded engineering view','Named components move apart along assembly axes without invented internals','Verified engineering drawings/CAD required; legacy feature text alone insufficient','Part dimensions and assembly constraints supplied by manufacturer','Locked 3/4 inspection position; no unrestricted orbit','Baked AO plus one key/rim','Actual metal/glass/control construction','None','No','GLB named nodes + .blend; optional approved SVG diagrams','Additional geometry staged after hero; hidden internals never loaded initially','Yes: approved 2D assembly diagram with same annotations','BLOCKED BY ASSET: TP-003. BLENDER ASSET REQUIRED. No fictional wiring or hidden hardware.'),
('TP-004','Blender / environment + lighting','Home entrance/floor','Architectural reveal','Premium industrial showroom; supports cabinet scale and negative space','Orion spatial staging; Lusion product-lighting reference; Tierplay model dimensions','Room scale determined from approved cabinet; floor at0, model grounded','Entrance spline2–4s desktop, shorter mobile; predetermined floor and screen anchors','Broad neutral soft source, darker architecture, baked indirect illumination','Dark graphite floor with controlled rough reflection; restrained architectural metal','No mandatory environmental loop','No','GLB room + baked lightmaps + environment HDR/EXR source and optimized derivative','Room+lighting ≤3MB compressed provisional; no real-time planar reflection on balanced','Yes: simplified geometry and baked floor lighting','BLENDER ASSET REQUIRED. No neon tunnel, fictional casino floor or decorative particle field.'),
('TP-005','Game media / edit existing video','Cabinet screen; games; Player Journey','Attract screen and authentic game presentation','Use approved actual game capture; correct board/game mapping','Five recovered Sunscape MP4s; correct board pages and original game assets','Native screen aspect from TP-001/002; 1080p master;720p delivery trial','Capture screen straight-on; no baked perspective inside display texture','Actual game colors; no invented win state','Digital screen content','6–10s quiet loop, continuous first/last frame, audio separate','No','H.264 MP4 + poster AVIF/WebP; optional WebM if justified','One active decode; target≤2MB clip; lazy after poster','Yes:720p or lower after device testing','Match games per GAME-MATRIX; sixth board unidentified. Do not generate gameplay, jackpot outcomes or unverified features.'),
('TP-006','Shader integration assets','Prototype screen entry','Glass-to-pixel crossing','Validated display UVs, mask, normal and anchors; optional subtle noise texture','TP-001 ScreenDisplay / ScreenGlass','UV0 unit square or documented curved mapping; screen-local transform','Dolly along display normal; scale from actual bounds','Reflection fades near plane; RGB structure only during approach','Glass IOR/roughness based on reference; emissive display','Transition1.2–2.2s, reversible; not video','Mask if needed','Model anchor metadata JSON + shader + optional small KTX2','No permanent postprocessing chain; at most one bounded half-resolution intermediate if profiling requires','Yes: simplified shader/direct cut on low/reduced motion','Shader may be coded at M03/04; asset prerequisite is true display geometry, not a guessed screen in a still.'),
('TP-007','Image generation / product still','Static/no-WebGL and boot','Faithful fallback artwork','Approved Altitude and Pinnacle front3/4, dark studio and alpha variants','Original model-specific photos or approved GLB renders only','3840×2160 master;2160×3840 portrait; derivative widths480/960/1600','50mm equivalent;1.35m camera; complete base and correct proportions','Soft key left, controlled rim right, soft grounded contact shadow','Reference-confirmed material appearance, smoked glass and display surface','None','Separate real-alpha variant required','PNG masters and optimized AVIF/WebP derivatives','Hero derivative target≤350KB at intended quality; no 4K mobile download','Yes: separately composed portrait','IMAGEGEN BRIEF ONLY this turn. Preserve geometry, display count, button layout, base and branding position. Existing dragon images unapproved for this use.'),
('TP-008','Image generation / game artwork enhancement','Games catalogue/detail','Higher-quality crops retaining game identity','Enhance lighting/resolution only, keep character/symbol identities and titles','Correct source game asset mapped to approved board','2048 square/landscape masters; final display crops from layout','Original recognizable composition; restrained depth','Color belongs to each real game, no blanket purple treatment','Preserve illustration style unless explicit reimagining approved','None','Only when compositing layer needed','PNG masters + AVIF/WebP derivative','≤150KB catalogue thumbnails target; load visible rows only','Yes: portrait crops without cutting title/subject','No new game names, symbols, mechanics or logos; identity review needed for generated work.'),
('TP-009','Diagram / source product UI','Products / TLJ / TCM','Explain existing capabilities','Approved topology and actual UI screenshots where needed','/products/; /player-journey/ source claims','Vector logical network; no claim of real-time production status','Fixed isometric or flat DOM/SVG view','Signals highlight one explained relationship','Neutral line/shape system tied to design tokens','Step-driven; motion only when explaining flow','SVG transparent','SVG + approved screenshot sources; cabinet LOD instances optional','DOM/SVG preferred; no duplicated model textures','Yes: vertical steps','Need product-owner confirmation: per-location TLJ semantics and TCM operations. Illustrative jackpot value must be explicitly illustrative, not a live figure.'),
('TP-010','Business content / documents / operational integration','Contact, support, all footers/game detail','Preserve conversion and legal/download functions','Valid flyers, legal URLs, sales/support recipients, states, consent text','Legacy CTA/form matrix','Accessible PDF flyer; HTML legal content; form field contract','Not applicable','Not applicable','Not applicable','None','No','PDF + approved text/URL configuration; endpoint contract','Forms lightweight; PDFs lazy downloads','Yes: accessible form and PDF','BLOCKED BY CONTENT/INTEGRATION: TP-010. No fake download/form-success or replacing form with mailto.'),
('TP-011','Verified editorial/social proof','Home testimonials/partners; news','Real attribution and editorial continuity','Approved quotes, permissions, identities; approved partner relationships only','Legacy placeholders are NOT valid testimonials','Original portrait/logo files if supplied; text first','Natural portrait only if genuinely relevant','Neutral; no invented person','Not applicable','None','Logo alpha if supplied','Approved copy/attribution + original images','No carousel or video needed','Yes','Current testimonial placeholders explicitly deprecated. No partner list in recovered home. Preserve intent without fabrication.'),
('TP-012','Audio production','Optional showroom sound','Quiet spatial feedback','Low-level room tone, cabinet hum, focus tone, screen-entry cue','Approved recordings or licensed original composition','48kHz master, mono positional cue/stereo room bed','Not applicable','Not applicable','Sonic restrained machinery; no casino win sounds as decoration','Room loop12–20s with seam-free zero crossings; one-shot cues≤1s','No','WAV masters; compressed Ogg/AAC delivery','Optional audio bundle≤500KB; fetch only on unmute','Yes; off by default','AUDIO ASSET REQUIRED if sound is adopted; no autoplay, user control and hidden-tab suspend.'),
('TP-013','Google Flow / cinematic video brief','Optional secondary product media','Pre-rendered approved product shot, not replacement for interactive cabinet','Short lighting reveal around validated Altitude; lock exact geometry','Approved TP-001 studio render start/end frames','1920×1080 delivery;4K master only if needed','50mm lens; slow8degree lateral arc at1.35m; camera path fixed','Soft key left, warm-neutral rim; no strobing','Reference-accurate matte shell/glass/metal','6s24fps; loop only if identical pose/light at first and last frame','No','MP4/WebM + poster + master','≤3MB clip target; entirely lazy, never boot-critical','Yes:portrait-safe shot or still','VIDEO BRIEF ONLY; no generation requested this turn. Negative: no distorted buttons, logos, extra screens, fictional gameplay, zoom pulse, glitch, morphing machinery. Start/end frames must be approved render, color neutral graphite/warm white.')]
s='# Asset requests\n\nPlanning only. Required media is never silently replaced. IDs are used by proposed sequence and milestone gates. Budgets are provisional targets, not measurements. Exact cabinet identity/dimensions come from the source owner, not generative inference.\n\n'
keys=['ASSET ID','TYPE','PAGE','SECTION','PURPOSE','SOURCE REFERENCE','DIMENSIONS','CAMERA','LIGHTING','MATERIALS','LOOP REQUIREMENT','ALPHA REQUIREMENT','OUTPUT FORMAT','OPTIMIZATION TARGET','MOBILE VERSION REQUIRED','NOTES']
for a in items:
 s+='## '+a[0]+'\n\n'+'\n\n'.join(k+': '+v for k,v in zip(keys,a))+'\n\n'
w('docs/assets/ASSET-REQUESTS.md',s)
w('docs/assets/BLENDER-PRODUCTION-BRIEF.md','''# Blender handoff — TP-001 / TP-002 / TP-003 / TP-004

BLENDER ASSET REQUIRED. No high-quality production GLBs are present. The image-based prototype cannot supply true occlusion, materials, exploded parts or camera-plane crossing.

Input package: model-specific front/side/back/top orthographic photos, full dimensions, actual screen geometry/curvature, controls/payment/speaker closeups, real material swatches, approved Tierplay logo vector, manufacturer CAD if available. Confirm all manufacturing details with product owner. Keep conflicting source claims in SOURCE-CONFLICTS until resolved.

Hierarchy for each model: Altitude or Pinnacle root → Body, Trim, ScreenGlass, ScreenDisplay, Controls, Buttons, Validator, Speakers, Lighting, Base, InternalDetails. Add anchors ScreenCenter, ScreenNormal, FocusCameraTarget, GroundContact. World units meters, Y-up, applied transforms, base at y0, documented forward axis. Parts pivot on actual assembly axes. Never add unobserved internals to satisfy a label.

Materials: PBR base color/metallic/roughness/normal/AO with correct color-space flags; display replaceable without replacing cabinet mesh. Glass separate and minimal overlapping transmission layers. Match product photos under neutral lighting before dramatic art direction. UV islands non-overlapping for baked maps; consistent texel density; small brand decals remain legible. No baked game graphics on body texture.

Deliver editable .blend, licensed texture/HDRI sources, GLB LOD0/1/2, KTX2 compressed textures and uncompressed references. Choose Meshopt by measured transfer/decode; Draco only if it wins actual decode/perceptual tradeoff. Validate loaders and texture formats across target browsers. Preserve silhouette and screen UV mapping across LODs.

Acceptance: compare model screenshots to reference at front/side/3quarter, verify dimensions/bounds/ground contact, inspect glass sorting and screen pixel alignment, test mesh naming and material swap, inspect all LODs, report triangles/draw calls/texture allocation/compressed transfer/decode time. Browser context-loss/reload must reconstruct correctly. Budget targets are in ASSET-REQUESTS; no unsupported claim that these counts guarantee performance.

Exploded assembly TP-003 starts only after verified internal drawings. Environment TP-004 uses baked indirect lighting and shared materials, shadow/contact grounding, architectural occlusion, no neon tunnel. Camera start/entry/floor/focus/crossing paths are reviewed in previs against actual geometry. Deliver one approved product still for static fallback from the same asset.
''')
w('docs/assets/IMAGE-GENERATION-BRIEF.md','''# Image generation requirements — briefs, not generation

TP-007 input roles: model-specific original cabinet photos are identity/geometry references; approved Blender render is the preferred composition target; original logo is branding reference. Do not use the current generated dragon cabinet as dimensional evidence.

Prompt contract: “Render the Altitude Tierplay cabinet strictly matching the supplied approved reference. 50mm equivalent front three-quarter lens, camera height1.35m, entire cabinet/base in frame. Large soft key camera-left, narrow controlled rim camera-right, subtle overhead reflection. Preserve reference-confirmed powder-coated shell/metal finish, smoked glass and gloss display. Minimal graphite studio, soft grounded contact shadow. Produce separate dark studio and true transparent-alpha variants, landscape3840×2160 and recomposed portrait2160×3840. Do not change geometry, display count, button/validator layout, base proportions, branding position or visible features. Do not add decorations, extra panels or generated gameplay.”

Use material terms only after reference confirmation. Compare result to original before approving; generative stills cannot replace GLBs. TP-008 uses individual verified game art as identity reference and preserves actual title/characters/symbols. Keep prompts and original outputs separate from optimized derivatives; record provenance and approval. No images were generated in the audit assignment.
''')
w('docs/assets/VIDEO-PRODUCTION-BRIEF.md','''# Video requirements

Prefer actual approved game capture for TP-005. Audit the five recovered MP4s for game/board identity, native dimensions, duration, rights and loop boundaries before screen use. A board filename is not proof of its actual contents. No generated gameplay or fictional outcomes.

Optional Google Flow shot TP-013: use approved cabinet render as both identity reference and start frame;50mm equivalent lens at1.35m,6seconds24fps, slow8degree lateral arc, neutral graphite color treatment, soft left key/right rim, complete cabinet inside frame. End frame must be supplied from approved same-geometry render. For a loop use matching camera pose/light at endpoints; otherwise deliver a deliberate non-looping settle. No geometry morph, extra screens, changing logos/buttons, strobe, glitch, win claims or imaginary mechanics. Deliver landscape and separately safe portrait compositions, MP4/WebM and optimized poster. See TP-013 for budget and role.

Video is optional supporting media and cannot satisfy the interactive 3D cabinet requirement. Build integration only after the audit/references gate; do not fake absent video using CSS motion.
''')
print('Asset briefs written')
